-- Shim. The real palette lives in the active theme.
--
-- edited by claude opus 5
-- palette moved into config/themes/<name>/palette.lua so it can be switched
--
-- conf/theme.lua still does `require("conf.palette")` and still gets a table
-- with accent/background/foreground, border_active/border_inactive and the
-- mix()/rgba() helpers -- the interface is unchanged. Only where the values
-- come from moved.
--
-- dofile, not require: require caches by module name, so a theme switch
-- followed by `hyprctl reload` would keep serving the previous theme's table
-- out of package.loaded. dofile re-reads every time.
return dofile("/home/monke/dotfiles/config/themes/current/palette.lua")
